import type { Metadata } from "next";
import Link from "next/link";
import { CodeBlock } from "@/components/code-block";
import { PageHero } from "@/components/page-hero";
import { nextItemSnippet, postEventSnippet, putItemSnippet } from "@/lib/snippets";

export const metadata: Metadata = { title: "Integration Guide", description: "A production-minded guide to integrating Adaptive Engine: credentials, identifiers, catalog sync, practice loop, retries, and rollout." };

const mapping = [
  ["learnerId", "A stable opaque ID generated by your backend. Never a name, email, or authentication token."],
  ["itemId", "Your existing question or activity identifier."],
  ["skill", "A stable hierarchical key such as mathematics:g4:number:fractions."],
  ["difficulty", "An integer from 1 to 5. Omit it to start with the neutral default of 3."],
  ["idempotencyKey", "The unique ID of your answer attempt. Reuse it for every retry of that event."],
];

function GuideStep({ number, title, summary, children }: { number: string; title: string; summary: string; children: React.ReactNode }) {
  return <article className="guide-step"><div className="guide-step-index"><span>{number}</span></div><div className="guide-step-body"><div className="guide-step-heading"><h2>{title}</h2><p>{summary}</p></div>{children}</div></article>;
}

export default function GuidePage() {
  return <>
    <PageHero eyebrow="Integration guide" title="Add the decision layer without disrupting the learning product." description="A production-minded path from test credentials to shadow mode and controlled rollout. The engine is backend-only; your application remains responsible for authentication, content, grading, and learner experience.">
      <div className="page-hero-actions"><Link href="/reference" className="button button-lime">Open API reference</Link><Link href="/developers" className="button button-ghost-dark">Developer hub</Link></div>
    </PageHero>
    <section className="guide-layout section-shell">
      <aside className="guide-toc"><span>On this page</span>{["Credentials", "Identifiers", "Item sync", "Practice loop", "Failure handling", "Safe rollout"].map((item, index) => <a key={item} href={`#step-${index}`}>{String(index).padStart(2, "0")} {item}</a>)}</aside>
      <div className="guide-content">
        <GuideStep number="00" title="Provision tenant credentials" summary="Use separate keys for local development, staging, and production."><div id="step-0" className="guide-callout"><strong>Keep the key server-side.</strong><p>Store it in a secret manager as <code>ADAPTIVE_SERVICE_API_KEY</code>. Never place it in a browser bundle, mobile application, public log, or <code>NEXT_PUBLIC_</code> variable. Plaintext keys are shown once; rotate a lost key rather than trying to recover it.</p></div></GuideStep>
        <GuideStep number="01" title="Define identifier mapping" summary="Stable identifiers are the foundation of a trustworthy learner model."><div id="step-1" className="mapping-table">{mapping.map(([concept, description]) => <div key={concept}><code>{concept}</code><p>{description}</p></div>)}</div></GuideStep>
        <GuideStep number="02" title="Synchronize item metadata" summary="Register only the metadata needed for selection."><div id="step-2"><CodeBlock code={putItemSnippet} title="upsert one item" /><div className="guide-notes"><p><strong>Bulk initial load</strong><span>POST /v1/items/bulk accepts up to 1,000 items atomically.</span></p><p><strong>Keep it current</strong><span>Upsert on create or edit; deactivate retired items without deleting history.</span></p><p><strong>Preserve the boundary</strong><span>Do not send question text, answer keys, media, or learner identity.</span></p></div></div></GuideStep>
        <GuideStep number="03" title="Wire the adaptive practice loop" summary="Request, teach, grade, report, and repeat."><div id="step-3" className="guide-code-stack"><CodeBlock code={nextItemSnippet} title="1 · request recommendation" /><div className="guide-inline-step"><span>2</span><p>Look up the returned <code>itemId</code> in your database, render the activity, and grade the answer using your existing rules.</p></div><CodeBlock code={postEventSnippet} title="3 · report outcome" /><div className="guide-inline-step"><span>4</span><p>Request the next item. The preceding outcome is already reflected in learner state.</p></div></div></GuideStep>
        <GuideStep number="04" title="Design for failure" summary="A recommendation dependency should not block the learner."><div id="step-4" className="failure-grid"><article><span>Timeout or 5xx</span><strong>Fall back locally</strong><p>Select an unseen eligible item from your own database and record telemetry.</p></article><article><span>Event timeout</span><strong>Retry safely</strong><p>Send the exact same idempotency key. The service returns the original result.</p></article><article><span>429</span><strong>Back off</strong><p>Respect the rate limit and retry after the advised interval.</p></article><article><span>404 next-item</span><strong>Repair scope</strong><p>Widen the requested scope or inspect catalog synchronization.</p></article></div></GuideStep>
        <GuideStep number="05" title="Roll out through shadow mode" summary="Compare before allowing the service to change learner experience."><div id="step-5" className="rollout-list">{[
          ["Sync", "Create a test tenant and synchronize the eligible catalog."],
          ["Shadow", "Call both the engine and current selection logic; show learners the current result only."],
          ["Compare", "Review bank coverage, reason codes, mastery trajectories, latency, and isolation."],
          ["Pilot", "Enable engine-driven selection for internal or designated test learners behind a flag."],
          ["Ramp", "Expand gradually while retaining the old path as an immediate rollback."],
          ["Learn", "Version backfills and algorithm changes. Never silently rewrite historical state."],
        ].map(([title, text], index) => <div key={title}><span>{index + 1}</span><p><strong>{title}</strong>{text}</p></div>)}</div></GuideStep>
        <div className="guide-finish"><span>Ready for the contract?</span><h2>Explore every request and response shape.</h2><Link href="/reference" className="button button-dark">Open API reference ↗</Link></div>
      </div>
    </section>
  </>;
}
