import type { Metadata } from "next";
import Link from "next/link";
import { PageHero } from "@/components/page-hero";

export const metadata: Metadata = { title: "Security & Privacy", description: "Adaptive Engine trust boundary, tenant isolation, credential handling, data minimization, and production security model." };

export default function SecurityPage() {
  return <>
    <PageHero eyebrow="Security and privacy" title="Collect less. Isolate rigorously. Explain every decision." description="The architecture minimizes the information required to personalize learning and keeps direct identity, content, and answer keys in the customer’s environment.">
      <div className="page-hero-actions"><Link href="/developers#architecture" className="button button-lime">View architecture</Link><Link href="/guide" className="button button-ghost-dark">Integration controls</Link></div>
    </PageHero>
    <section className="security-principles"><div className="section-shell"><div className="section-heading"><div><span className="eyebrow">Trust model</span><h2>Security starts with a narrow product boundary.</h2></div></div><div className="principle-grid"><article><span>01</span><h3>Backend only</h3><p>Tenant keys stay in server-side secret storage. Browser and mobile clients never call the service directly.</p></article><article><span>02</span><h3>Pseudonymous learners</h3><p>The API accepts stable opaque learner identifiers—not names, emails, birthdates, or customer authentication tokens.</p></article><article><span>03</span><h3>Metadata, not content</h3><p>Item IDs, skill keys, difficulty, grade band, and tags are enough. Question content and answer keys stay with the tenant.</p></article><article><span>04</span><h3>Auditable decisions</h3><p>Selections and outcomes retain algorithm versions and reasons so recommendation behaviour can be reconstructed.</p></article></div></div></section>
    <section className="control-section"><div className="section-shell control-columns"><div><span className="eyebrow eyebrow-light">Implemented controls</span><h2>Controls in the current service.</h2><ul><li>Hashed API keys with prefixes, scopes, expiry, and revocation</li><li>Constant-time key-hash verification</li><li>Tenant ID included in persistence keys and database queries</li><li>Composite foreign keys prevent cross-tenant references</li><li>Schema validation and bounded request bodies</li><li>Secure response headers and per-key rate limiting</li><li>Transactionally idempotent answer events</li><li>No public browser integration surface</li></ul></div><div><span className="eyebrow eyebrow-light">Production operations</span><h2>Controls required around every deployment.</h2><ul><li>Managed encrypted PostgreSQL with tested backups</li><li>Least-privilege database roles and network restrictions</li><li>Centralized logs, metrics, traces, and incident alerts</li><li>Formal key rotation and tenant offboarding procedures</li><li>Documented retention, export, and deletion workflows</li><li>Independent threat modelling, load testing, and security review</li><li>Data residency and contractual controls matched to each customer</li><li>Database row-level security as additional defence in depth</li></ul></div></div></section>
    <section className="boundary-detail"><div className="section-shell"><div className="section-heading"><div><span className="eyebrow">Data inventory</span><h2>Know exactly what crosses the boundary.</h2></div></div><div className="inventory-grid"><div className="inventory-yes"><span>Processed by Adaptive Engine</span><ul><li>Tenant and API-key identifiers</li><li>Opaque learner identifier</li><li>Item and skill identifiers</li><li>Difficulty and optional scope metadata</li><li>Correct or incorrect outcome</li><li>Mastery state and recommendation audit</li></ul></div><div className="inventory-no"><span>Not required by Adaptive Engine</span><ul><li>Learner names and email addresses</li><li>Birthdates and demographic profiles</li><li>Question text, choices, and media</li><li>Correct answers and grading rubrics</li><li>Customer passwords or session tokens</li><li>Payment or subscription information</li></ul></div></div><p className="security-caveat"><strong>Important:</strong> data minimization reduces risk; it does not remove every privacy or regulatory obligation. Each customer must assess its own use case, jurisdiction, contracts, retention needs, and learner-consent requirements.</p></div></section>
  </>;
}
