import type { Metadata } from "next";
import Link from "next/link";
import { PageHero } from "@/components/page-hero";

export const metadata: Metadata = { title: "Pricing", description: "Adaptive Engine commercial model for sandbox evaluation, design partners, growing learning products, and enterprise deployments." };

const tiers = [
  { name: "Sandbox", label: "Evaluate", price: "Free during evaluation", description: "Explore the contract and validate a server-side integration with non-production data.", features: ["Test tenant and restricted key", "Item metadata synchronization", "Recommendation and event APIs", "OpenAPI contract", "Community documentation"], cta: "Read the guide", href: "/guide", tone: "plain" },
  { name: "Design Partner", label: "Pilot", price: "Pilot scope", description: "Direct support for teams prepared to run a structured adaptive-learning pilot and share product feedback.", features: ["Architecture and mapping session", "Guided implementation review", "Shadow-mode comparison plan", "Outcome and guardrail definition", "Direct product feedback channel"], cta: "Request access", href: "/design-partner", tone: "lime" },
  { name: "Growth", label: "Operate", price: "Usage aligned", description: "For learning products moving from pilot to recurring production recommendations and learning events.", features: ["Production tenant and key rotation", "Recommendation and mastery APIs", "Usage and operational reporting", "Standard support", "Published service targets"], cta: "Discuss requirements", href: "/design-partner", tone: "plain" },
  { name: "Enterprise", label: "Scale", price: "Annual agreement", description: "For organizations with procurement, data-residency, support, and operational-control requirements.", features: ["Environment and access controls", "Contractual service commitments", "Security and architecture review", "Data-residency planning", "Priority support and onboarding"], cta: "Start a conversation", href: "/design-partner", tone: "dark" },
];

export default function PricingPage() {
  return <>
    <PageHero eyebrow="Commercial model" title="Start with evidence. Scale with usage." description="The platform is in an early commercial phase. Pricing is structured around evaluation, a focused pilot, recurring API usage, and enterprise operating requirements—not inflated seat counts or hidden content fees." />
    <section className="pricing-section"><div className="section-shell"><div className="pricing-note"><span>Early commercial model</span><p>Final production pricing is confirmed against request volume, support needs, deployment requirements, and pilot scope. No customer should pay for question content the platform does not host.</p></div><div className="pricing-grid">{tiers.map((tier) => <article key={tier.name} className={`pricing-card pricing-${tier.tone}`}><span>{tier.label}</span><h2>{tier.name}</h2><strong>{tier.price}</strong><p>{tier.description}</p><ul>{tier.features.map((feature) => <li key={feature}>✓ {feature}</li>)}</ul><Link href={tier.href}>{tier.cta} <i>↗</i></Link></article>)}</div></div></section>
    <section className="usage-section"><div className="section-shell usage-grid"><div><span className="eyebrow">How usage works</span><h2>Meter decisions and learning events—not learner identity.</h2><p>A production plan can align to the API activity that creates value: eligible-item recommendations, accepted answer events, and optional analytics. The exact combination should be validated with early customers.</p></div><div className="usage-meters"><article><span>Recommendation</span><strong>One next-item decision</strong><small>Selected item + reason + algorithm version</small></article><article><span>Learning event</span><strong>One accepted outcome</strong><small>Idempotent mastery update</small></article><article><span>Analytics</span><strong>Optional reporting layer</strong><small>Mastery and tenant skill summaries</small></article></div></div></section>
    <section className="pricing-faq"><div className="section-shell"><div className="section-heading"><div><span className="eyebrow">Commercial FAQ</span><h2>Questions buyers usually ask first.</h2></div></div><div className="faq-grid"><article><strong>Do you charge for storing content?</strong><p>No. The platform stores item metadata, not question content, choices, media, or answer keys.</p></article><article><strong>Is Sandbox production-ready?</strong><p>No. It is for evaluation with non-production data and does not include production service commitments.</p></article><article><strong>Can we start with one course?</strong><p>Yes. A narrow, measurable learner loop is usually a stronger pilot than a broad catalog migration.</p></article><article><strong>Are prices public yet?</strong><p>Not as fixed dollar amounts. The current goal is to validate usage, support, and procurement needs with design partners before publishing misleading tiers.</p></article></div></div></section>
  </>;
}
